version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: test
          command: | 
            npm i
            npm test

workflows:
  heroku_deploy:
    jobs:
      - test
          filters:
            tags:
              only: /.*/
      # - heroku/deploy-via-git:
      #     requires:
      #       - test
